### ISSUE TITLE
Error: Contact system admin.

### ISSUE THREAD

**Issue by ZandercraftGames** [mike-matera/osTicket-helm#1]
Firstly, just wanted to say that this helm chart is amazing! Thank you so much!

Currently I'm having an issue where osTicket is giving me a fairly non-descriptive error: `Error: Contact system admin.`. There doesn't seem to be any errors logged on the server itself, so I'm just trying to figure out what specifically may be causing the osTicket installation to be inoperable. Below is my deployment:

```
adminEmail: <REDACTED>
adminFirstName: Zander
adminLastName: <REDACTED>
adminPassword: <REDACTED>
adminUsername: <REDACTED>
affinity: {}
global:
  storageClass: longhorn
autoscaling:
  enabled: false
  maxReplicas: 100
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
fullnameOverride: ''
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/mike-matera/osticket-helm
imagePullSecrets: []
ingress:
  annotations:
    cert-manager.io/issuer: <REDACTED>-support
  className: 'traefik'
  enabled: true
  hosts:
    - host: <REDACTED>
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
memcached:
  enabled: false
mysql:
  architecture: standalone
  auth:
    database: osticket
    password: <REDACTED>
    rootPassword: <REDACTED>
    username: <REDACTED>
  secondary:
    persistence:
      enabled: true
    replicaCount: 1
nameOverride: ''
nodeSelector: {}
ostEmail: support@<REDACTED>
ostName: <REDACTED> Support
podAnnotations: {}
podSecurityContext: {}
replicaCount: 1
resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 256Mi
securityContext: {}
service:
  port: 80
  type: ClusterIP
serviceAccount:
  annotations: {}
  create: true
  name: ''
timezone: America/Toronto
tolerations: []

```
